# Generated by Django 4.0.4 on 2022-05-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('nombreSkin', models.CharField(max_length=50, verbose_name='Nombre de la skin')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='Nombre de usuario ')),
                ('imagenSkin', models.ImageField(null=True, upload_to='skins')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('fechaNac', models.CharField(max_length=50, verbose_name='Fecha de nacimiento')),
                ('contra', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
    ]
