# Generated by Django 4.0.4 on 2022-06-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGEZ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio2', models.IntegerField(verbose_name='Precio')),
                ('nombreSkin2', models.CharField(max_length=50, verbose_name='Nombre de la skin')),
                ('nombreUsuario2', models.CharField(max_length=50, verbose_name='Nombre de usuario ')),
                ('imagenSkin2', models.ImageField(null=True, upload_to='skins')),
            ],
        ),
        migrations.CreateModel(
            name='Producto3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio3', models.IntegerField(verbose_name='Precio')),
                ('nombreSkin3', models.CharField(max_length=50, verbose_name='Nombre de la skin')),
                ('nombreUsuario3', models.CharField(max_length=50, verbose_name='Nombre de usuario ')),
                ('imagenSkin3', models.ImageField(null=True, upload_to='skins')),
            ],
        ),
    ]
