# Generated by Django 4.0.4 on 2022-06-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGEZ', '0003_alter_usuario_nombreusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJuego', models.CharField(max_length=50, verbose_name='Nombre del juego')),
                ('imagenJuego', models.ImageField(null=True, upload_to='skins')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenSkin',
            field=models.ImageField(blank=True, null=True, upload_to='skins'),
        ),
    ]
