# Generated by Django 4.0.4 on 2022-06-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGEZ', '0004_juego_alter_producto_imagenskin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenSkin',
            field=models.ImageField(null=True, upload_to='skins'),
        ),
    ]
