# Generated by Django 4.0.4 on 2022-06-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGEZ', '0005_alter_producto_imagenskin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJuego2', models.CharField(max_length=50, verbose_name='Nombre del juego')),
                ('imagenJuego2', models.ImageField(null=True, upload_to='skins')),
            ],
        ),
        migrations.CreateModel(
            name='Juego3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJuego3', models.CharField(max_length=50, verbose_name='Nombre del juego')),
                ('imagenJuego3', models.ImageField(null=True, upload_to='skins')),
            ],
        ),
    ]
