# Generated by Django 4.0.4 on 2022-06-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGEZ', '0006_juego2_juego3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagenJuego',
            field=models.ImageField(null=True, upload_to='juegos'),
        ),
        migrations.AlterField(
            model_name='juego2',
            name='imagenJuego2',
            field=models.ImageField(null=True, upload_to='juegos'),
        ),
        migrations.AlterField(
            model_name='juego3',
            name='imagenJuego3',
            field=models.ImageField(null=True, upload_to='juegos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contra',
            field=models.CharField(max_length=50, unique=True, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Correo'),
        ),
    ]
